export default () => ({
  RawSqlHerokuConfig: {
    type: 'postgres' as const,
    host: process.env.POSTGRES_HEROKU_HOST,
    port: 5432,
    username: process.env.POSTGRES_HEROKU_USER,
    password: process.env.POSTGRES_HEROKU_PASSWORD,
    database: process.env.POSTGRES_HEROKU_DATABASE,
    autoLoadEntities: true,
    synchronize: false,
    ssl: { rejectUnauthorized: false },
  },
  TypeOrmHerokuConfig: {
    type: 'postgres' as const,
    host: process.env.POSTGRES_HEROKU_HOST,
    port: 5432,
    username: process.env.POSTGRES_HEROKU_USER,
    password: process.env.POSTGRES_HEROKU_PASSWORD,
    database: process.env.POSTGRES_HEROKU_DATABASE,
    autoLoadEntities: true,
    synchronize: false,
    ssl: { rejectUnauthorized: false },
  },
  PostgresLocalConfig: {
    type: 'postgres' as const,
    host: process.env.POSTGRES_HEROKU_HOST,
    port: 5432,
    username: process.env.POSTGRES_LOCAL_USER,
    password: process.env.POSTGRES_LOCAL_PASSWORD,
    database: process.env.POSTGRES_LOCAL_DATABASE,
    autoLoadEntities: true,
    synchronize: false,
    ssl: { rejectUnauthorized: false },
  },
});
